version: '3.10'

services:
  v1:
    ports:
      - '0.0.0.0:8085:8080'
    build:
      context: .
      dockerfile: application/Dockerfile
    command: sh -c "gunicorn -w 4 -k uvicorn.workers.UvicornWorker core.v1:app --bind=v1:8080"
